language: python
sudo: false


branches:
  only:
    - master


matrix:
  include:
    - python: pypy
      env: TOX_ENV=trial-pypy-tw132
    - python: pypy
      env: TOX_ENV=trial-pypy-tw140
    - python: pypy
      env: TOX_ENV=trial-pypy-tw150
    - python: pypy
      env: TOX_ENV=trial-pypy-tw155
    - python: pypy
      env: TOX_ENV=trial-pypy-twcurrent
    - python: pypy
      env: TOX_ENV=trial-pypy-twtrunk

    - python: 2.7
      env: TOX_ENV=trial-py27-tw132
    - python: 2.7
      env: TOX_ENV=trial-py27-tw140
    - python: 2.7
      env: TOX_ENV=trial-py27-tw150
    - python: 2.7
      env: TOX_ENV=trial-py27-tw155
    - python: 2.7
      env: TOX_ENV=trial-py27-twcurrent
    - python: 2.7
      env: TOX_ENV=trial-py27-twtrunk

    - python: 3.3
      env: TOX_ENV=trial-py33-tw155
    - python: 3.3
      env: TOX_ENV=trial-py33-twcurrent
    - python: 3.3
      env: TOX_ENV=trial-py33-twtrunk

    - python: 3.4
      env: TOX_ENV=trial-py34-tw155
    - python: 3.4
      env: TOX_ENV=trial-py34-twcurrent
    - python: 3.4
      env: TOX_ENV=trial-py34-twtrunk

    - python: 3.5
      env: TOX_ENV=trial-py35-tw155
    - python: 3.5
      env: TOX_ENV=trial-py35-twcurrent
    - python: 3.5
      env: TOX_ENV=trial-py35-twtrunk

    - python: 2.7
      env: TOX_ENV=pyflakes
    - python: 2.7
      env: TOX_ENV=twistedchecker-diff
    - python: 2.7
      env: TOX_ENV=docs
    - python: 2.7
      env: TOX_ENV=docs-linkcheck

  allow_failures:
    - env: TOX_ENV=trial-py27-twtrunk
    - env: TOX_ENV=trial-py33-twtrunk
    - env: TOX_ENV=trial-py34-twtrunk
    - env: TOX_ENV=trial-py35-twtrunk
    - env: TOX_ENV=trial-pypy-twtrunk

    - env: TOX_ENV=twistedchecker-diff
    - env: TOX_ENV=docs-linkcheck


install:
  - pip install tox coverage codecov


script:
  - tox -e "${TOX_ENV}"


after_success:
  - coverage combine
  - codecov
